spring:
  application:
    name: ffmpeg-service
  threads:
    virtual:
      enabled: true

server:
  port: 8081

minio:
  url: ${MINIO_URL}
  user: ${MINIO_USER}
  password: ${MINIO_PASSWORD}
  bucket: ${MINIO_BUCKET}

streaming:
  ffmpeg-path: /usr/bin/ffmpeg
  hls-segment-duration: 2
  hls-segment-count: 8

callback:
  url: ${STREAMING_CALLBACK_URL}
