server:
  port: 8082

spring:
  threads:
    virtual:
      enabled: true

streaming:
  ffmpeg-path: ${STREAMING_FFMPEG_PATH:ffmpeg}
  hls-path: ${STREAMING_HLS_PATH:/hls}
  mediamtx-url: ${STREAMING_MEDIAMTX_URL:rtmp://mediamtx:1935}
  hls-segment-duration: ${STREAMING_HLS_SEGMENT_DURATION:2}
  hls-segment-count: ${STREAMING_HLS_SEGMENT_COUNT:4}
