server:
  port: 8082

spring:
  threads:
    virtual:
      enabled: true

streaming:
  ffmpeg-path: ${STREAMING_FFMPEG_PATH}
  hls-path: ${STREAMING_HLS_PATH}
  hls-segment-duration: ${STREAMING_HLS_SEGMENT_DURATION}
  hls-segment-count: ${STREAMING_HLS_SEGMENT_COUNT}
  mediamtx-url: ${MEDIAMTX_URL}
  rtmp-user: ${MEDIAMTX_RTMP_PUBLISH_USER}
  rtmp-pass: ${MEDIAMTX_RTMP_PUBLISH_PASS}
