worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 80;

        # HLS ao vivo — serve do volume local
        location /hls {
            alias /hls;
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }

        # VOD — proxy pro MinIO
        location /vod {
            # access_by_lua_block {
            #     local jwt   = require "resty.jwt"
            #     local token = ngx.var.cookie_stream_token

            #     if not token then
            #         ngx.log(ngx.WARN, "stream_token ausente")
            #         return ngx.exit(401)
            #     end

            #     local f = io.open("/etc/nginx/certs/public.pem", "r")
            #     if not f then
            #         ngx.log(ngx.ERR, "chave pública não encontrada")
            #         return ngx.exit(500)
            #     end
            #     local public_key = f:read("*all")
            #     f:close()

            #     local jwt_obj = jwt:verify(public_key, token)

            #     if not jwt_obj.verified then
            #         ngx.log(ngx.WARN, "JWT inválido: ", jwt_obj.reason)
            #         return ngx.exit(403)
            #     end
            # }

            proxy_pass http://minio:9000/vod;
            proxy_set_header Host minio:9000;

            proxy_hide_header Access-Control-Allow-Origin;
            proxy_hide_header Access-Control-Allow-Methods;
            proxy_hide_header Access-Control-Allow-Headers;

            add_header Access-Control-Allow-Origin * always;
            add_header Accept-Ranges bytes always;
            add_header Cache-Control "public, max-age=3600" always;

        }

        # API Spring Boot
        location / {
            proxy_pass http://spring-boot:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # CORS
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;

            # Preflight
            if ($request_method = OPTIONS) {
                return 204;
            }
        }
    } 
    server {
        listen 9000;

        location / {
            proxy_pass http://minio:9000;
            proxy_set_header Host minio:9000;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # força ignorar o host do cliente
            proxy_pass_header Server;
            client_max_body_size 0;
            proxy_buffering off;
            proxy_request_buffering off;
        }
    }   
}
