worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 80;

        # HLS — segmentos gerados pelo FFmpeg
        location /hls {
            alias /hls;
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }

        # Arquivos de filmes e séries
        location /files {
            alias /data;
            add_header Accept-Ranges bytes;
            add_header Access-Control-Allow-Origin *;
        }

        # API Spring Boot
        location / {
            proxy_pass http://spring-boot:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
