spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:iptv}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  cache:
    type: simple

  threads:
    virtual:
      enabled: true

server:
  port: 8080

jwt:
  private-key-location: classpath:certs/private.pem
  expiration: 3600

tmdb:
  api-key: ${TMDB_API_KEY}
  base-url: https://api.themoviedb.org/3
  language: pt-BR

xtream:
  server:
    url: ${SERVER_URL:localhost}
    port: ${SERVER_PORT:80}
    https-port: ${SERVER_HTTPS_PORT:443}
    protocol: ${SERVER_PROTOCOL:http}
    rtmp-port: ${SERVER_RTMP_PORT:1935}
    timezone: America/Sao_Paulo
