spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  cache:
    type: simple

  threads:
    virtual:
      enabled: true

server:
  port: 8080

jwt:
  private-key-location: classpath:certs/private.pem
  expiration: 3600

cors:
  allowed-origins:

internal:
  secret: ${INTERNAL_SECRET}

streaming:
  ffmpeg-service-url: ${STREAMING_FFMPEG_SERVICE_URL}
  rtmp-publish-user: ${MEDIAMTX_RTMP_PUBLISH_USER}
  rtmp-publish-pass: ${MEDIAMTX_RTMP_PUBLISH_PASS}

tmdb:
  api-key: ${TMDB_API_KEY}
  base-url: https://api.themoviedb.org/3
  language: pt-BR
  image-base-url: https://image.tmdb.org/t/p/w500
  backdrop-base-url: https://image.tmdb.org/t/p/w1280

admin:
  default:
    username: ${ADMIN_DEFAULT_USERNAME}
    password: ${ADMIN_DEFAULT_PASSWORD}
    email: ${ADMIN_DEFAULT_EMAIL}

minio:
  url: ${MINIO_URL}
  public-url: ${MINIO_PUBLIC_URL}
  user: ${MINIO_USER}
  password: ${MINIO_PASSWORD}
  bucket: ${MINIO_BUCKET}

xtream:
  session:
    duration-hours: ${XSTREAM_SESSION_DURATION_HOURS}
  server:
    url: ${SERVER_URL}
    port: ${XSTREAM_SERVER_PORT}
    https-port: ${SERVER_HTTPS_PORT}
    protocol: ${SERVER_PROTOCOL}
    rtmp-port: ${SERVER_RTMP_PORT}
    timezone: ${SERVER_TIMEZONE}

logging:
  level:
    com.duduzgomes: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
