rtmpAddress: :1935
hls: false

authMethod: http
authHTTPAddress: http://spring-boot:8080/internal/mediamtx/auth
authHTTPExclude:
  - action: api
  - action: metrics
  - action: pprof

paths:
  "~^live/.*":
    source: publisher
    runOnReady: curl -X POST "http://spring-boot:8080/internal/mediamtx/publish?streamKey=$MTX_PATH"
    runOnNotReady: curl -X POST "http://spring-boot:8080/internal/mediamtx/onUnpublish?streamKey=$MTX_PATH"
